/** Native `title` text for the controls. Hover text only; accessible names live on `aria-label`. */
export const TIP = {
  move: 'Move item',
  expand: 'Expand children',
  collapse: 'Collapse children',
  complete: 'Mark complete',
  incomplete: 'Mark incomplete',
  showDetails: 'Show details',
  hideDetails: 'Hide details',
  edit: 'Edit item',
  add: 'Add item under',
  delete: 'Delete item',
  newItem: 'New item',
  signOut: 'Sign out',
  hideCompleted: 'Hide completed items',
  cancel: 'Cancel',
  settings: 'Settings',
  nightMode: 'Night mode',
  useDevice: 'Use device setting',
  gapSmall: 'Small gap',
  gapMedium: 'Medium gap',
  gapLarge: 'Large gap',
  done: 'Done',
} as const;
